version: "3.9"

services:
  cli-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: graphyn-cli-server:latest
    container_name: graphyn-cli-server
    environment:
      NODE_ENV: production
      # API endpoint for CLI to connect to
      API_BASE_URL: ${API_BASE_URL:-https://api.graphyn.xyz}
      # OAuth configuration for CLI authentication
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID:-graphyn-cli}
      OAUTH_DEVICE_FLOW_URL: ${OAUTH_DEVICE_FLOW_URL:-https://api.graphyn.xyz/auth/device}
      # Server configuration
      PORT: ${PORT:-8004}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "${PORT:-8004}:8004"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped